version: '3.8'

services:
  ui:
    container_name: ui
    image: strtwalker/bdiplus-demo-ui:v1
    ports:
      - 3000:3000

  app:
    container_name: app
    image: strtwalker/bdiplus-demo-app:v1
    ports:
      - 8080:8080
    environment:
      - PG_HOST=postgres

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

